// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAmh6iAbu2zRNaBOAtm378-RvGgdtHH5A',
    appId: '1:65191878306:web:fdfef57c6166a16c4941fb',
    messagingSenderId: '65191878306',
    projectId: 'android-catalogo-pelis',
    authDomain: 'android-catalogo-pelis.firebaseapp.com',
    storageBucket: 'android-catalogo-pelis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXWiA4npmL9ISRY-8S_DYu7M3-PwELgG0',
    appId: '1:65191878306:android:2eedace0cc0afb894941fb',
    messagingSenderId: '65191878306',
    projectId: 'android-catalogo-pelis',
    storageBucket: 'android-catalogo-pelis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYippxWqxmMOYZoP1Qr8L-6aiy1ZtJ6P8',
    appId: '1:65191878306:ios:206e8fe9a9af62c24941fb',
    messagingSenderId: '65191878306',
    projectId: 'android-catalogo-pelis',
    storageBucket: 'android-catalogo-pelis.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYippxWqxmMOYZoP1Qr8L-6aiy1ZtJ6P8',
    appId: '1:65191878306:ios:206e8fe9a9af62c24941fb',
    messagingSenderId: '65191878306',
    projectId: 'android-catalogo-pelis',
    storageBucket: 'android-catalogo-pelis.firebasestorage.app',
    iosBundleId: 'com.example.catalogoPeliculasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAmh6iAbu2zRNaBOAtm378-RvGgdtHH5A',
    appId: '1:65191878306:web:6a44c515686b739a4941fb',
    messagingSenderId: '65191878306',
    projectId: 'android-catalogo-pelis',
    authDomain: 'android-catalogo-pelis.firebaseapp.com',
    storageBucket: 'android-catalogo-pelis.firebasestorage.app',
  );
}
